import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";

export const metadata: Metadata = {
  title: "My Project",
  description: "Generated by create next app",
  keywords: ['HTML', 'CSS', 'TypeScript'],
  openGraph: {
    images: ['https://static.vecteezy.com/ti/vetor-gratis/p1/8214517-abstract-geometric-logo-or-infinity-line-logo-for-your-company-gratis-vetor.jpg']
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
